### ISSUE TITLE
Content file not being created

### ISSUE THREAD

**Issue by SuperSandro2000** [xarantolus/Collect#39]
I am not sure what you what to know so:

I get this:
```
Error 500
ENOENT: no such file or directory, open 'public/s/content.json'
```

Have this installed:
```
npm -v
5.8.0
nodejs -v
v8.11.4
```

and run this to start
```
sudo npm start production
```

**Comment by xarantolus** [comment]
Thanks for the report.

Usually the server should ignore if the file doesn't exist and assume that there are zero entries in the archive.
I tried installing the server from scratch using the same node version (but on Windows) and was able to start it without problems, so I'm not sure if this can help you:

* Add a site to the archive by going to `http://yourserver:port/new` directly and entering any site you want. The content file is first created when the server finished downloading the first entry. After this, the error might go away.

* You could create the file at `/path/to/Collect/Collect/public/s/content.json` manually. The default content for this file is `[]`. After a restart (or even just a website reload) the website should display that there are no sites in the archive.

* If it is related to some kind of permission error (maybe when creating the file; but this should log an error to the console) you might get a different result when changing permissions of the `s` directory; but I believe that this is not the case as you used `sudo`

* The last option I can think of would be using a different node version. I use node `v10.14.2` and npm `6.4.1` on a Raspberry Pi and haven't encountered this problem yet

**Comment by xarantolus** [comment]
I think the problem was that it only checked a specific error number that seems to only work on Windows. From now on, the server automatically generates the file so that it always exists, but it also checks the more generic error code `ENOENT` if it doesn't.

If you want to test it on your system, you can download the new version and see if it still throws the error if the file doesn't exist. (But watch out, if you delete the content.json file all directories with websites will be deleted automatically, so it might be better to install it somewhere else and delete it after that)

**Comment by SuperSandro2000** [comment]
works now.
I don't know if you have tests but maybe you should think about doing some or test it from time to time on linux on a server or vm just to make sure that the program works.
